#!/bin/bash
#yum install -y httpd24
sudo chown -R ec2-user:www /var/www/html

sudo find /var/www/html -type d -exec sudo chmod 777 {} +
#sudo find /var/www/html -type f -exec sudo chmod 644 {} +
sudo chmod -R 777 /var/www/html/storage
sudo chmod -R 777 /var/www/html/bootstrap

composer update -d /var/www/html