#!/bin/bash
#yum install -y httpd24

php /var/www/html/artisan clear-compiled
php /var/www/html/artisan optimize
php /var/www/html/artisan view:clear
php /var/www/html/artisan cache:clear

sudo chown -R ec2-user:apache /var/www/html

sudo find /var/www/html -type d -exec sudo chmod 755 {} +
sudo find /var/www/html -type f -exec sudo chmod 644 {} +
#sudo chmod -R 777 /var/www/html/public
#sudo chmod -R 777 /var/www/html/bootstrap
#sudo chmod -R 777 /var/www/html/storage
sudo chgrp -R apache storage bootstrap/cache
sudo chmod -R ug+rwx storage bootstrap/cache

composer update -d /var/www/html